Replace `execute_command` with specific redis functions when possible
redis/redis-om-python pull request #346
Opened 2022-08-11 14:18 UTC by dvora-h

2022-08-11 14:52 UTC, chayim commented on aredis_om/model/model.py
> +        await db.json().set(self.key(), ".", json.loads(self.json()))
instead of "." perhaps we should use the json.root_path?

2022-08-11 14:52 UTC, chayim requested changes
Just the one comment

2022-08-12 12:22 UTC, simonprickett approved these changes
Looks good to me - I looked over the code and ran tests on my machine.

2022-08-14 08:52 UTC, chayim approved these changes

2022-08-22 15:04 UTC, merged